version: "3.9"
services:
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"

  create_keyspace:
    image: cassandra
    volumes:
      - ./utils:/app
    entrypoint: /app/create_keyspace.sh
    depends_on:
      - cassandra

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
      - create_keyspace

  ui:
    build: ./ui
    ports:
    - "80:3000"
    environment:
      - API_BASE_URL=app
    depends_on:
      - app