name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cassndra
        run: |
          java -version
          echo "deb http://downloads.apache.org/cassandra/debian 40x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
          curl https://downloads.apache.org/cassandra/KEYS | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y cassandra
          sleep 30
          nodetool status

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish code coverage
        uses: codecov/codecov-action@v1.5.2
        with:
          directory: ./build/reports/jacoco/test/